### ISSUE TITLE
Bug? SVG image is draggable if you encapsulate it with a link 

### ISSUE THREAD

**Issue by Kevin-at-Navigram** [uikit/uikit#3690] opened 2018-12-10 09:46 UTC
### UIkit version
3.0.0-rc.25

### Browser
Firefox Developer Edition 65
Chromium 70

### Reproduction Link
[CodePen](https://codepen.io/kevin-at-navigram/pen/MZWRVb)
[Gist](https://gist.github.com/Kevin-at-Navigram/ce8565088c92bab2ed453e0625d63fb0)

### What is Expected?
I expected that with `uk-link-reset`, the image behaviour would remain unchanged by the hyperlink. 

### What is actually happening?
The image behaviour is changed, and it's now user-selectable and draggable

### is it a bug?
I think it is, because the expectations of the [link functionality](https://getuikit.com/docs/link#link-reset) does give the impression that such image behaviour would remain unchanged. It would also be quite annoying if menu items become draggable because they have an <a> defined around them.

**Comment by aarongerig** [comment] 2018-12-10 10:21
This is not a bug! A link, whether it contains an image or not, can be dragged either into the url bar of the browser or onto your desktop to create a hyperlink. This is default browser / OS behavior and therefore totally fine.

I'm closing this for now, feel free to reopen, if you think I misunderstood your problem.

**Closed by aarongerig** 2018-12-10 10:21 UTC
