### ISSUE TITLE
Slider with Lazy Load Images?

### ISSUE THREAD

**Issue by hansnolte** [uikit/uikit#1319] opened 2015-06-08 13:35 UTC
Is it possible to create the slider with Lazy Load Images?

Do I need a Third-Party-Plugin or is it with On-Board-Plugin (maybe Scrollspy) ?

Thanks in advance
Hans

**Comment by malles** [comment] 2015-06-08 17:02
You could try to adapt this pen for use i slider. I think it should work: http://codepen.io/malles/pen/vOXzxZ

**Comment by hansnolte** [comment] 2015-06-09 08:08
Hi malles,

many thanks for your response.

But with my limited Javascript knowledge, I do not think I get it to run.

Do you have a tip for a external lazy loading script?

**Comment by malles** [comment] 2015-06-09 11:06
Hmm, I'm afraid not. It might be interesting to build it in the slider component as an option. For a slider it's an obvious performance winner.
@aheinze Maybe allow a `data-source` attribute on image and lazyload those when coming into view?

**Comment by hansnolte** [comment] 2015-06-09 11:36
"For a slider it's an obvious performance winner."
 I totally agree!

I'm just testing "lazysizes"
https://github.com/aFarkas/lazysizes

**Comment by ne-u** [comment] 2015-06-13 08:49
+1

**Comment by Pandahisham** [comment] 2015-06-13 12:03
+1 I think a simple plugin to lazyload any image anywhere would be an added bonus

**Comment by ne-u** [comment] 2015-06-15 12:46
@hansnolte is lazysizes working?

**Comment by hansnolte** [comment] 2015-06-15 13:39
Hi ne-u,
I have only tested shortly.
My customer did not want a slider anymore, but a Lightbox.

I think It's a kind of "defer".
The images are not loaded on demand, but in series.
(If I did everything right)

**Comment by aheinze** [comment] 2015-11-23 10:40
I think this should be easily fixed by using an exiisting 3rd party lazyloader script.

**Closed by aheinze** 2015-11-23 10:40 UTC

**Comment by freefri** [comment] 2018-01-18 13:40
Does anyone recommend an easy to integrate lazy load plug-in, not only for the slider but general for every image?

**Comment by viocassel** [comment] 2018-01-18 13:52
Just use [lazysizes](https://github.com/aFarkas/lazysizes).

**Comment by ladislavsulc** [comment] 2018-01-21 14:17
Also for lightbox videos (button on click), it loads too much JS before the video is even clicked. Any suggestions, please?

**Comment by ladislavsulc** [comment] 2018-01-21 14:43
Okay, bend the theme in WP with Lazysizes. It works! Thank you.

**Comment by ladislavsulc** [comment] 2018-01-21 15:07
Okay, I have discovered one problem @viocassel. When I use [lazysizes](https://github.com/aFarkas/lazysizes) it requires attribute data-src. If I use modal with an iframe (YT video) and change it to data-src, closing the modal will not stop the video. It still plays in the background. I validated it is caused by this because when I change the iframe to only **src**, it works again. I guess some JS problem connected to src and `uk-video`?

Anyone a suggestion how to solve this? I don't want to use lightbox element for this.

Thank you.

**Comment by marcosdipaolo** [comment] 2018-03-23 04:32
and what  about lazy loading div's background images in uikit slider? is it posible with any script?

**Comment by viocassel** [comment] 2018-05-18 14:55
Just use new [Image component](https://getuikit.com/docs/image) 💪
