### ISSUE TITLE
When used with uk-breadcrumb, the dropdown element is still displayed.

### ISSUE THREAD

**Issue by xemania** [uikit/uikit#4263] opened 2020-08-13 15:45 UTC
### UIkit Version

*Check if the issue is reproducible with the latest stable version.*
3.5.6

### Actual Behavior

*What happened? Screenshots please, if relevant!*

### Expected Behavior

*What should have happened?*

### Reproduction Link

*A minimal Codepen that can reproduce the bug. Start with this [Codepen template](http://codepen.io/anon/pen/XMpryM)*

### Steps to Reproduce the Problem

1.When used with uk-breadcrumb, the dropdown element is still displayed.

**Comment by zzseba78** [comment] 2020-10-23 16:11
Duplicate of this: https://github.com/uikit/uikit/issues/4278

**Comment by janschoenherr** [comment] 2021-01-26 12:56
Fixed in 3.6.13

**Closed by janschoenherr** 2021-01-26 12:56 UTC
Labels: ! Bug
