### ISSUE TITLE
Modal an Tab Key: Question

### ISSUE THREAD

**Issue by luetn** [uikit/uikit#1424] opened 2015-07-31 15:33 UTC
Is it possible to enclose tab behaviour when a modal is open to the modal only?
If you have a form behind the modal it is painstaking to toggle from cancel to the save button (and back) in the modal "window" when you just use the keyboard as input.

**Comment by malles** [comment] 2015-07-31 16:25
duplicate of #1420

**Closed by malles** 2015-07-31 16:25 UTC
