### ISSUE TITLE
Spinner does not work in IE

### ISSUE THREAD

**Issue by SteppingHat** [uikit/uikit#2817] opened 2017-08-03 03:40 UTC
### UIkit version
3.0.0-beta.28

### Browser
IE 10, IE 11, Edge

### Reproduction Link
`<div uk-spinner></div>`

### Steps to reproduce
Visit https://getuikit.com/docs/spinner in IE 11, IE 10 and Edge

### What is Expected?
The spinner is supposed to animate in a circle motion

### What is actually happening?
IE10/11 - It stays as a fixed circle
Edge - It animates very differently

**Comment by nordbit** [comment] 2017-08-10 16:43
Dynamically added under Firefox 54.0.1 is displayed as display:hidden or display:none. Dunno, no single "display" properties but Firebug shows div with spinner as hidden

**Comment by ratiofu** [comment] 2017-09-03 23:27
Observing the same thing. This issue is a duplicate of #2533. According to @mzdr's [comment](https://github.com/uikit/uikit/issues/2533#issuecomment-318594589), it looks like IE11 is a no-go with the current approach, but it would still be nice to get it working correctly in Edge.

**Closed** 2017-12-13 09:29 UTC

**Comment by hrvojegolcic** [comment] 2019-06-30 21:49
According to supported browsers IE 11 should work. But it doesn't. Why is this issue closed?

**Comment by SuperKrevette** [comment] 2020-03-31 13:06
@hrvojegolcic, you are right.. I was going to create a todo about it...

I dont know whats the worst: a framework that says it support IE11 (but not really) or someone that closes an issue without giving any answer or solution.

**Comment by mzdr** [comment] 2020-03-31 15:04
It’s closed because it’s duplicate. See https://github.com/uikit/uikit/issues/2446
