### ISSUE TITLE
slideshow autoplay issue

### ISSUE THREAD

**Issue by flihub** [uikit/uikit#3691] opened 2018-12-11 11:52 UTC
autoplay should not stop when user click on it with this settings
uk-slideshow="animation: fade; autoplay: true; draggable: false; pause-on-hover: false; ratio: 7:3;"

### UIkit version
3.0.0-rc.25

### Browser
Chrome 71

### Reproduction Link
https://codepen.io/anon/pen/oJgKqp

### Steps to reproduce
click on slideshow

### What is Expected?
autoplay should not stop

### What is actually happening?
autoplay stopped

**Comment by hoppingmadZH** [comment] 2018-12-20 07:54
At least the slideshow should restart after a while or have the possibility to set a delay to do so. As the YOOtheme support told me stopping is not a bug but a feature. Unfortunately restarting the slideshow does not work with UIkit.slideshow(element).startAutoplay(); 
If you have clicked the slideshow once you cannot restart it again. If you haven't you can start and stop by script (as you can see here http://yoo.browsertablette.ch/17 )

**Comment by janschoenherr** [comment] 2018-12-20 10:33
@hoppingmadZH this should be resolved with the latest dev version. Thanks.

**Comment by joeyslack** [comment] 2019-02-22 02:02
Issue still exists

**Closed** 2019-07-10 10:07 UTC
