### ISSUE TITLE
Box-sizing to all elements by default

### ISSUE THREAD

**Issue by PixelT** [uikit/uikit#1128] opened 2015-04-01 20:25 UTC
Why the box-sizing: border-box isn't applied to all elements by default?
Something like this:
```
*, 
*:before, 
*:after {
    box-sizing: border-box;
}
```

**Comment by zslabs** [comment] 2015-04-06 14:21
Dupe of https://github.com/uikit/uikit/pull/948 Add your +1 there

**Closed** 2015-04-13 12:51 UTC
