### ISSUE TITLE
Please add Telegram icon to icons

### ISSUE THREAD

**Issue by dsancheznet** [uikit/uikit#4266] opened 2020-08-16 11:28 UTC
### Summary

Please add Telegram icon to the icon component.

### Priority

Telegram is growing very quickly on the IM market and considering that the latest iconset does even include a G+ icon which isn't available for individuals anymore, Telegram should really be included asap. The icon does exist in the fontawesome font.

Thanks in advance

**Comment by AmirNzh** [comment] 2020-08-16 15:11
yes, It's very good suggestion.  👍

**Comment by gitingwar** [comment] 2023-05-03 06:01
The Tg icon is very necessary. Please add it

**Comment by janschoenherr** [comment] 2023-08-01 09:02
Duplicate of #3350

**Closed by janschoenherr** 2023-08-01 09:02 UTC
Labels: ! Feature
