### ISSUE TITLE
Tooltip doesn't work with disabled buttons

### ISSUE THREAD

**Issue by Clindbergh** [uikit/uikit#1458] opened 2015-08-14 11:33 UTC
Adding a disabled tag to the button will break the tooltip:
```
<button class="uk-button" data-uk-tooltip title="" disabled>...</button>
```

**Comment by malles** [comment] 2015-08-14 11:54
Duplicate of https://github.com/uikit/uikit/issues/422
Unfortunately, disabled buttons don't fire any events.

**Closed by malles** 2015-08-14 11:54 UTC
