### ISSUE TITLE
New icon 'telegram'

### ISSUE THREAD

**Issue by myshoeshurt** [uikit/uikit#3350] opened 2018-04-27 19:21 UTC
Please add a new icon for the chat platform telegram.

Thank you!

**Comment by rangka-kacang** [comment] 2018-04-28 01:52
Duplicate of #3340

Reference #2421

**Comment by myshoeshurt** [comment] 2018-04-30 10:02
How is that a duplicate for a basket icon?

**Comment by rangka-kacang** [comment] 2018-05-01 05:29
Because you are asking to bloat the icon js not everyone need what you need. Your problem does not rely in the core but can easily be solved by extending it yourself. This is uikit not another fontawesome clone.

**Comment by ladislavsulc** [comment] 2019-01-28 17:30
Telegram is such a hugely popular service that it deserves its own icon.

**Closed** 2024-03-01 07:28 UTC
