### ISSUE TITLE
3.0.0-beta.25 - Spinner does not work in IE11

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [uikit/uikit#2720] opened 2017-06-13 19:54 UTC
### UIkit version

3.0.0-beta.25

### Browser
Internet Explorer 11
### Reproduction Link

https://codepen.io/anon/pen/OgXexP or https://getuikit.com/docs/spinner
### Steps to reproduce
Navigate to the [spinner section](https://getuikit.com/docs/spinner) in the documentation.
### What is Expected?
Spinner should actually spin.
### What is actually happening?
A static gray circle is drawn. No spinning motion is present.

**Comment by mzdr** [comment] 2017-07-28 08:32
Duplicate of #2533.

**Closed** 2017-12-13 08:54 UTC
