### ISSUE TITLE
icons render twice in accordion

### ISSUE THREAD

**Issue by alterkater** [uikit/uikit#2441] opened 2017-02-23 08:08 UTC
but only when first within multiple elements.

thanks,

**Comment by lukashl** [comment] 2017-02-23 08:56
In alert and others also...

**Comment by alterkater** [comment] 2017-02-23 11:29
and only FF (current) it seems.

**Comment by janschoenherr** [comment] 2017-03-01 17:12
Fixed in Beta 13.

**Comment by dsignr** [comment] 2017-04-12 18:33
This issue still persists.

**Comment by janschoenherr** [comment] 2017-04-13 09:09
Please add a reproduction link. Thanks.

**Comment by rossity** [comment] 2017-05-03 15:15
@janschoenherr this happens with me, but may be vue related, and it only happens to `uk-close`

**Comment by ruchern** [comment] 2017-05-03 15:27
> may be vue related

I havet he same problem when on Vue.

**Comment by Propaganistas** [comment] 2017-05-04 20:39
I was also experiencing double (and sometimes even tripled) icons, but it only seems to be the case if the JS is added in `<head>`.  Moving it into the body fixed it for me, but adding `defer` to the `<script>` tag and keeping it in head also works apparently:

```
<head>
    <script src="/assets/js/uikit.min.js" defer></script>
    <script src="assets/js/uikit-icons.min.js" defer></script>
</head>
```

```
<body>
    <script src="/assets/js/uikit.min.js"></script>
    <script src="assets/js/uikit-icons.min.js"></script>
</body>
```

**Comment by dsignr** [comment] 2017-05-04 21:08
I must also add all your observations are consistent with mine as I also have Vue in my setup. @janschoenherr I will send a reproduction link soon here.

**Comment by rossity** [comment] 2017-05-10 10:48
Hey guys, has anyone made some progress on how to fix this? 

@Propaganistas unfortunately I am using Laravel Mix and compiling all of my JS files into a single "app,js" file, including UiKit and Vue, so I don't want to move my JS to the bottom!

**Comment by Propaganistas** [comment] 2017-05-10 11:44
As a quick response:
@rossity I'm also using Laravel Mix. Just extract the vendor bundles into another file, which is generally considered best practice as vendor libraries don't change that often and hence remain cached.

```js
mix.js('resources/assets/js/app.js', 'js')
   .extract(['ui', 'vue'], 'js/vendor');
```
```html
<head>
   ...
   <script src="/js/vendor.js" defer></script>
</head>
<body>
   ...
   <script src="/js/app.js"></script>
</body>
```
// End of thread hijack - sorry

**Comment by Propaganistas** [comment] 2017-05-10 11:49
@rossity https://laravel.com/docs/master/mix#vendor-extraction

**Closed** 2017-07-21 09:09 UTC

**Comment by SaphiLC** [comment] 2018-09-13 22:36
still bugged, using vue, javascript is in the head, not defered because i dont want the users seeing a broken page until uikit loads and styles margins, grids, etc, the jumping of the elements is just annoying... also since you FORCE some icons inside some trigger classes its an extra headache to remove those.... could you PLEASE make the icons truly optional??
example
from this:
```
<a class="uk-alert-close" uk-close></a>
```
to this:
```
<a class="uk-alert-close" uk-close>
your icon here, uikit's or 3rd party
</a>
```
