### ISSUE TITLE
Add plug-in to Brackets Editor

### ISSUE THREAD

**Issue by APakrohk** [uikit/uikit#3894] opened 2019-06-26 03:15 UTC
Brackets : A modern, open source text editor that understands web design.
With focused visual tools and preprocessor support, Brackets is a modern text editor that makes it easy to design in the browser. It's crafted from the ground up for web designers and front-end developers.

Plz Make Uikit plugin for Brackets

**Comment by janschoenherr** [comment] 2019-06-26 07:38
duplicate of #2208

**Closed by janschoenherr** 2019-06-26 07:38 UTC
