### ISSUE TITLE
IE11: Switcher: switch to other container item when select text in uk-switcher list

### ISSUE THREAD

**Issue by YuliaGrigorieva** [uikit/uikit#1122] opened 2015-03-31 10:10 UTC
I have found this issues specific only for IE. It is perfectly reproducible on IE11.
It is also seen here: http://getuikit.com/docs/switcher.html in any examples:

For example, first example:
I selecting "Hello!" by mouse:
![capture1](https://cloud.githubusercontent.com/assets/8545374/6916668/e4856f76-d7a6-11e4-8fc7-3ab29d4d491f.PNG)
As far as I release the mouse button, it is automatically switched to other tab:
![capture2](https://cloud.githubusercontent.com/assets/8545374/6916709/29c888e8-d7a7-11e4-9a11-37b3d379d6cf.PNG)

**Comment by stebeg** [comment] 2015-04-13 11:31
Seems to be a duplicate of #1092

**Comment by aheinze** [comment] 2015-04-13 14:34
this should be fixed with the upcoming release.

**Closed by aheinze** 2015-04-13 14:34 UTC
Labels: bug
