### ISSUE TITLE
Request: Another bring back width-*-10 request

### ISSUE THREAD

**Issue by OwenMelbz** [uikit/uikit#2602] opened 2017-04-15 09:42 UTC
It seems many people have already requested this to be bought back, I was hoping to bring up the issue again how the 10 grid allows a much easier development experience of being able to finely tune grids.

I've seen people posting custom polyfills for this by extending it and using hooks etc, but for something that many people use on regular projects, having to manually do this for each project seems overkill, as well as forcing them to add another step into their build processes.

So a few questions really regarding this

- Can we have it back?
- What is the reason for not having it?
- Why was it removed?
- What would be the problem with adding it back in?

**Comment by Riddler84** [comment] 2017-04-18 18:33
You have basically a few options to compensate this. I don't really miss the 10 Grid classes ;)

1. Nested Grids allows you to have any number of grid items per row as you want.
2. The new `uk-width-auto` and `uk-width-expand` classes gives you great flexibility and you can mix them with the normal uk-width-classes.

**Comment by OwenMelbz** [comment] 2017-04-18 18:53
Hey, thanks for the reply. Although this doesn't really answer any of the questions, or solve any of the issues people would be having.

`uk-width-auto` and `uk-width-expand` are not a solution to situations where you would want something like `uk-width-1-10 and uk-width-9-10`. Sure you can do `uk-width-1-6 and uk-width-expand` but thats not the same. Thats a completely different solution.

And nesting grids doesn't allow for as clean markup. As you said means you gotta do a bunch of nesting, when HTML should be used for defining the structure, not appearance. This is EXACTLY what css is for. So why try do it with HTML? Having a few lines of cacheable css seems to be a much nicer solution, is much more readable and maintainable, 12 months down the line seeing a `1-10 and 9-10` is more obvious than what seem randomly nested divs. Which also adds extra overhead to CMS projects where repeatable elements are required to be embedded.

**Comment by zzseba78** [comment] 2017-04-18 19:55
I vote for get the 10th grid back... i miss it. In my opinion **the grid is the base to build upon**, every bit that improves the grid is worth it.
And it would be nice to have the redundat grid size removed to, they make the workflow faster.

**Comment by Riddler84** [comment] 2017-04-19 15:01
Ok you're both right. If you need columns with exactly 10, 20, 30% and so on, you can't achieve this with uikit3 at the moment, unless you write custom css on top. So, i understand the wish to have it back. 

Personally, i'm totally fine with the actual grid and width components, because i haven't used the 10th classes before.

**Comment by OwenMelbz** [comment] 2017-04-20 11:01
For those who want a stop-gap and have stumbled across this post - there is a polyfill for it which I converted into a npm package for users https://github.com/OwenMelbz/uikit3-extra-widths

**Comment by janschoenherr** [comment] 2017-12-12 16:48
This is a duplicate of https://github.com/uikit/uikit/issues/2593

**Closed by janschoenherr** 2017-12-12 16:48 UTC
