### ISSUE TITLE
Performance degradation for DOM elements created in runtime (data opbservers).

### ISSUE THREAD

**Issue by ArturLew** [uikit/uikit#2924] opened 2017-10-10 14:07 UTC
### UIkit version
3.0.0-beta.30

### Browser
Recent Google Chrome (61.0.3163.100)

### Reproduction Link
https://codepen.io/anon/pen/dVejRY

### Steps to reproduce
1. Generate lot of DOM elements (e.g. table with 25 columns and 25 rows) in runtime using Vue or Angular. See an example.

### What is Expected?
Rendering of UIKit elements should be much better for this simple scenario.
Other frameworks (e.g. Bootstrap) are handling this scenario without any performance problems.

### What is actually happening?
Big performance degradation is observed. Most time the browser spends in UIKit JavaScript code (data observers and attaching and detaching events).
Another problem is related to icon duplication. Explanations that it is necessary to change the order of attaching scripts are not very professional;)

### Notes
Optimize a way how data observers are handled.

This issue is connected with data observers used in UIKit. Thiss issue was noticed by user krajniol:
in https://github.com/uikit/uikit/issues/1796 and indeed, there is no problem in previous versions.

Problem doesn't exist in Bootstrap. Above example run using Bootstrap notation is blazing fast.

**Comment by bck2207** [comment] 2019-09-20 17:07
Hi,
We have a similar problem in one of our projects. I tried to find out, what was making the rendering of our list view that slow. At the end, like mentioned above, the main reason was the `MutationObserver`, which is observing the whole `document` with `childList`, `subTree`, `attributes` and `characterData`. When I commented out that part from `boot.js`, it was like 99% faster.

As a temporary solution I built an additional function to `UIkit`-Object to switch that observer on or off. Before rendering a list with a lot of elements, `MutationObserver` will be disconnected with `UIkit.disconnectMainObserver()` and after the rendering is done `UIkit.connectMainObserver()` will be called, which registers UIkit on new elements again and starts observing.

It's a tricky issue and comparing it with Bootstrap isn't helping. But maybe giving users an option to temporarily switch off the observers is not a bad idea at all, since it isn't a breaking change.

I can make a pull request when it's sounds OK.

**Comment by janschoenherr** [comment] 2019-09-30 09:41
@ArturLew The issue is due to UIkits icon system using inline SVGs. In your case you are rendering 25 * 30 * 5 = 3750 inline SVG elements. This is costly. In cases like these it would probably be better to simply not use the Icon component, but reference the SVG image directly.

@bck2207 Is your issue related to the many icons too? If not, please provide a codepen for us to inspect the issue. Thanks.

**Comment by hueman567** [comment] 2020-01-21 21:50
This performance issue is killing me... unfortunately it's not as simple as building a codepen as we have a fairly complicated site that also uses knockoutjs. Lists with 50 or so items take 10 seconds to load, perhaps longer...

I've removed any use of svg icons as mentioned above so I doubt it's a problem

I'm using uikit to format tables as well as lists of divs(with sub-divs, etc). What I'm really looking for is the means to disconnect uikit from MutationObserver and reconnect again. At the very least it will serve as an effective confirmation of the problem...

I've attempted to understand @bck2207's solution but it seems beyond me at the moment.

I really like uikit and we have many hours invested in it but we're at the desperation point... is there any way you can help?

**Comment by janschoenherr** [comment] 2020-01-22 08:35
@hueman567 could you send me a message on discord and provide a link to a site, where I can inspect the issue?

**Comment by macbeth** [comment] 2020-01-22 13:10
we are experiencing a similiar issue. Uikit  use way too much cpu when embedeed in a page with large tables (>1000 rows) even if there isn't any uikit class used inside the page. Seems related to MutationObserver. Can you provide an api to disconnect the MutationObserver from the dom before the page ended to render, and reconnect it when the rendering has ended  ?

**Comment by viocassel** [comment] 2020-01-22 13:20
+1

**Comment by bck2207** [comment] 2020-01-22 13:25
So, sorry for late response.

The main problem with disconnecting observer is, that it doesn't really works when the rendered content goes in to a newly appended uikit-modal, since the modal component won't be initialized correctly in that case without workarounds. Long story short, it's not an utterly helpful solution.

As much I can see from the code, MutationObserver is needed to check newly appended elements, so the possible UI-Kit JS-Components can be detected and initialized immediately. I personally can't see a replacement, which works as good but still performs better. There can be some approaches, but all of them might require some bigger changes and intensive testing.

My solution was lazy-loading the content after all, so the amount of elements appended to the DOM initially is reduced. Of course, this is also another workaround but fits to our project.

**Comment by janschoenherr** [comment] 2020-01-22 13:35
@bck2207 Thanks for you reply. 
@macbeth, @viocassel Could you provide us with a reproduction link?

**Comment by bck2207** [comment] 2020-01-22 13:44
@hueman567 @macbeth 
To be able to address the change that I made, I found the repo of forked uikit in our own git repo. I only made the following change in boot.js

```js
    function init() {

        const observer = new MutationObserver(mutations => mutations.forEach(applyMutation));

        const observe = (isInitial) => {
            apply(document.body, connect);
            if (isInitial) {
                // Safari renders prior to first animation frame
                fastdom.flush()
            }
            observer.observe(document, {
                childList: true,
                subtree: true,
                characterData: true,
                attributes: true
            });
        }
        const disconnect = () => {
            observer.disconnect();
        }

        observe(true);

        UIkit.disconnectDocumentObserver = disconnect;
        UIkit.connectDocumentObserver = () => observe();
        UIkit._initialized = true;
    }
```
Basically, changed the init method in src/js/api/boot.js ;)

**Comment by hueman567** [comment] 2020-01-22 22:41
thanks for the great feedback and ideas. I'll work the problem more on our end and be back with some feedback

**Comment by hueman567** [comment] 2020-01-23 01:43
I've implemented @bck2207 's technique for disconnecting / connecting UIkit from the DOM and it has helped, but we're not there yet.

This is on a fairly fast 2017 iMac in Safari or Chrome. Also, all data is pre-loaded in the browser for these tests so there are no server / network / latency issues here.

We're using the Datatables.net table and for a list of 84 items, laying it out on screen took 11.2 seconds (!). If we disconnect, then render the table, then reconnect, it drops to 4 seconds. 

Obviously that's a great improvement and obviously that's still way too slow. It's possible that the delays are coming from other areas (knockoutjs or Datatables or something inefficient in our code) so I'll now embark on creating a stripped-down isolating page.

**Comment by macbeth** [comment] 2020-01-23 14:38
Here a zip with a small table. According Chrome Profiler, uikit use something like 70% of the scripting time (7 seconds) . Removing uikit classes doesn't help at all. Removing js uikit library returns the page to normal rendering performances (obviusly without the desidered look)

https://drive.google.com/open?id=1ksa9U_5s1OSFWbOxzUGQ0MQTE7ti1lfw

**Comment by janschoenherr** [comment] 2020-01-24 16:19
Could you please give the latest dev release a try. There should be less initial updates in your case.

UIkit version:
3.3.1-dev.0d26a0e66

**Comment by hueman567** [comment] 2020-01-26 04:29
That's definitely an improvement. The 11.2 second render has been shortened to about 2.5 seconds. That's still only for 84 items though and we often have lists with 100-300 items.

Is there more that can be done?

**Comment by janschoenherr** [comment] 2020-01-27 08:23
@hueman567 That's hard to tell without a reproduction link. I doubt, it's just the 84 rows though.

**Comment by hueman567** [comment] 2020-01-29 09:04
@janschoenherr, I have a reproduction link available for you. What is your discord id?

**Comment by janschoenherr** [comment] 2020-01-29 10:24
That would be Jan#0565

**Comment by janschoenherr** [comment] 2020-01-29 16:36
I believe this issue has been resolved with the latest dev version. Feel free to comment if the issue persists.

**Closed by janschoenherr** 2020-01-29 16:36 UTC

**Comment by ArturLew** [comment] 2020-01-29 20:25
@janschoenherr I'll check it soon :)

To be honest, I'll say that UIKit's performance is a bit problematic in my projects (I've been using it recently mainly with Vue + AgGrid).
From what I saw, most of my (others?) problems are related to mutation observers in UIKit.
For example, naked AgGrid offers blazing fast performance - but with UIKit (for projects with grid 30 x 30, approx. 2-3K of elements in DOM) results in a drastic reduction of the frame rate.
I don't observe such behaviour for ugly Bootstrap ;) or other libraries like ElemeFE/element.

Maybe it's not this thread, but what's the reason of keeping a small, custom icons library while e.g. Font Awesome/Material Icons offers several times better performance than SVG in UIKit?

**Comment by macbeth** [comment] 2020-02-03 15:08
Ok i can confirm that there is a huge performance improvement in the current dev trunk
