### ISSUE TITLE
Beta 36 breaks modal when activating via Javascript API 

### ISSUE THREAD

**Issue by TomS-** [uikit/uikit#3128] opened 2018-01-12 14:18 UTC
### UIkit version

3.0.0-beta.36

### Browser
Chrome (but I imagine this exists on all)

### Reproduction Link
https://getuikit.com/docs/modal#modal-dialogs

### Steps to reproduce
1. Open up the Dialog
2. Close it
3. .uk-modal-page is still applied to html DOM element. 

### What is Expected?
.uk-modal-page should be removed from HTML

### What is actually happening?
.uk-modal-page is not removed from HTML

**Comment by TomS-** [comment] 2018-01-12 14:29
For those who want to use .36 and need a fix for this you can use:
```
UIkit.modal.dialog(d);
$(".uk-modal").on("hide", function() {
    $("html").removeClass("uk-modal-page");
});
```
for jQuery or 
```
UIkit.modal.dialog(d);
document.querySelector(".uk-modal").addEventListener("hide", function() {
    document.querySelector("html").classList.remove("uk-modal-page");
});
```
for vanilla.

**Comment by janschoenherr** [comment] 2018-01-15 09:32
As mentioned above, it's a duplicate of #3132 and will be fixed asap.

**Closed by janschoenherr** 2018-01-15 09:32 UTC
