### ISSUE TITLE
Where is the Date and Time Picker?

### ISSUE THREAD

**Issue by frogydiak** [uikit/uikit#2789] opened 2017-07-20 03:28 UTC
Sorry if I'm asking this here but where is the Date and Time Picker? There's no way to customize the current <input type="date" /> I can't find JS and CSS that refers to it also. 

Nothing in the documentation as well. In test, there's only one javascript option for form.

**Comment by florianletsch** [comment] 2017-07-20 07:59
The datepicker is currently only available in UIkit 2 (https://getuikit.com/v2/docs/datepicker.html), but it has not been ported to UIkit 3 yet.

**Comment by frogydiak** [comment] 2017-07-24 04:12
Thanks for clarifying that @florianletsch. Can you confirm that UIKit 3 will not use HTML 5 form field?

**Comment by martinapixelwiese** [comment] 2017-11-17 12:29
hello, i am wondering -  will the datepicker be integrated into uikit 3 - and when? i am really looking forward to integrate it! thank you! :)

**Comment by jelgervisser** [comment] 2017-11-21 08:46
Hi, any news on this subject?

**Comment by johnclittle** [comment] 2017-11-27 16:03
+1

**Comment by amaradrys** [comment] 2017-12-08 15:31
+1

**Comment by lucakuehne** [comment] 2017-12-08 17:34
+1

**Comment by janschoenherr** [comment] 2017-12-12 16:10
This seems to be a duplicate of #2789

**Closed by janschoenherr** 2017-12-12 16:10 UTC

**Comment by NiteshOswal** [comment] 2017-12-14 06:46
Isn't this #2789? It's a duplicate of itself?

**Comment by Valexr** [comment] 2017-12-25 17:06
+1

**Comment by arwy18** [comment] 2018-01-05 18:14
+1

**Comment by sstarasenko** [comment] 2018-01-18 12:24
+1

**Comment by mexus** [comment] 2018-01-18 23:39
+1

**Comment by Sixstep** [comment] 2018-01-20 23:59
+1

**Comment by Mat-thieu** [comment] 2018-01-22 13:33
+1

**Comment by pepijnverburg** [comment] 2018-01-22 22:16
+1

**Comment by Viach** [comment] 2018-01-31 14:57
+

**Comment by arnvanhoutte** [comment] 2018-02-03 11:08
+1

**Comment by Viach** [comment] 2018-02-03 16:05
now I use this picker - https://github.com/colinmcintyre/datetimepicker
but I will be very glad to use picker from UIkit  framework

**Comment by viocassel** [comment] 2018-02-03 17:36
@Viach better to temporarily use [Flatpicker](https://github.com/chmln/flatpickr) 🤘

**Comment by Viach** [comment] 2018-02-03 18:00
@viocassel Thank you!

**Comment by samuelkarani** [comment] 2018-06-14 11:12
me too

**Comment by stell** [comment] 2018-07-04 18:42
+1
(is this still on your list or is a calendar component not coming for uikit3?)

**Comment by aarongerig** [comment] 2018-07-04 19:15
I don‘t think Date/Time picker will come to UIkit 3.

**Comment by gam6itko** [comment] 2018-10-24 16:33
any news @florianletsch ?

**Comment by stell** [comment] 2018-10-24 16:50
I don't think this will happen. You should consider an alternative...picker.

**Comment by DrYurets** [comment] 2022-05-07 10:43
Hello from 2022, guys!
