### ISSUE TITLE
UIkit 3 - Error in svg file path in css version.

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2202] opened 2017-01-10 13:51 UTC
There is an error in the **css file**, the svg image path it´s wrong

It shows
```
.uk-icon::before {
  background-image: url("../../dist/images/icons.svg");
}
```
and it should be
```
.uk-icon::before {
  background-image: url("../images/icons.svg");
}
```

**Comment by janschoenherr** [comment] 2017-01-10 15:49
Fixed with 20e02879c6bc81c7dcd489a3b2b9fe56da0aca50

**Closed by janschoenherr** 2017-01-10 15:49 UTC

**Comment by cocodrino** [comment] 2017-01-16 01:43
Hi @janschoenherr !!..I've just downloaded uikit 3 (^3.0.0-beta.2) from npm and I'm getting the same error...

my main less file is like this 
```less

@import "../node_modules/uikit/src/less/uikit.less";
@import "../node_modules/uikit/src/less/uikit.theme.less";

```

the error is

```shell

ERROR in ./~/css-loader?sourceMap!./~/less-loader!./styles/entry.less
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/uikit/dist/images/search-navbar.svg in /ho
me/yo/Documentos/proyectos/js/uikitBase/reaxor2/reaxor/styles
 @ ./~/css-loader?sourceMap!./~/less-loader!./styles/entry.less 6:72713-72775

ERROR in ./~/css-loader?sourceMap!./~/less-loader!./styles/entry.less
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/uikit/dist/images/search-large.svg in /hom
e/yo/Documentos/proyectos/js/uikitBase/reaxor2/reaxor/styles
 @ ./~/css-loader?sourceMap!./~/less-loader!./styles/entry.less 6:73401-73462

ERROR in ./~/css-loader?sourceMap!./~/less-loader!./styles/entry.less
```

I notice than the compiled less file show a similar code to @zzseba78 
styles/entry.css
4427:  background-image: url("../../../dist/images/accordion-open.svg");
10198:  background-image: url("../../../dist/images/accordion-open.svg");

in the past I'd a similar issue which was fixed changing the path in the uikit file as show [this](http://stackoverflow.com/questions/31493716/webpack-less-error-it-cant-resolve-ttf-and-woff2-files-from-uikit) response

hope you can help me here..thank so much!!

**Comment by semencov** [comment] 2017-01-25 13:58
The problem is because the whole `dist` folder is in `.npmignore`, so when you install UIkit from npm, you have only `src`, not `dist`. Current workaround is to specify github repository as the dependency:

```
"dependencies": {
  "uikit": "uikit/uikit"
}
```

In this case npm ignores `.npmignore`.

Hope it will be fixed soon.

**Comment by ChrisIgel** [comment] 2017-01-28 17:43
+1
