### ISSUE TITLE
Off-canvas autoclose issue when uk-scroll

### ISSUE THREAD

**Issue by xonixmx** [uikit/uikit#4000] opened 2019-10-10 11:50 UTC
The Off-canvas sidebar do not auto close after link was clicked if an internal link has the attribute 'uk-scroll'

**Comment by Morrison52** [comment] 2019-10-11 11:17
Can you close this issue as is a duplicate of #4001 and to solve this problem see [my comment](https://github.com/uikit/uikit/issues/4001#issuecomment-541022251) there. Note i marked this as dublicate because in #4001 the issue has proper format.

**Closed** 2019-10-11 11:23 UTC
