### ISSUE TITLE
Modal & Lightbox closing issue

### ISSUE THREAD

**Issue by Lumelomser** [uikit/uikit#3065] opened 2017-11-29 21:44 UTC
### UIkit version

3.0.0-beta.35

### Browser

Apple Safari (11.0, macOS 10.13.1)
Google Chrome (62.0, macOS 10.13.1)
Mozilla Firefox (56.0, macOS 10.13.1)

### Reproduction Link

https://codepen.io/anon/pen/aVQmgJ

### Steps to reproduce

Open the reproduction link.
Open the Modal by clicking on the example button.
Open the Lightbox from the Modal by clicking on the example link inside the Modal.
Close the Lightbox by using the 'ESC'-Key.

### What is Expected?

The Modal is still open.

### What is actually happening?

Both, the Lightbox and the Modal have been closed.

I haven't tested on Windows yet because it seems to be an UIKit specific, not OS specific issue.

**Comment by janschoenherr** [comment] 2017-12-13 15:10
Duplicate of #3064

**Closed by janschoenherr** 2017-12-13 15:10 UTC
