### ISSUE TITLE
Lightbox with sortable 

### ISSUE THREAD

**Issue by SimonWayne** [uikit/uikit#1244] opened 2015-05-08 19:06 UTC
Hello,
the Lightbox don't work within the sortable container.
The Picture load after the click normally.

Thanks for help!

**Comment by malles** [comment] 2015-05-09 14:17
Known issue, duplicate of #1193 and #1132.
Still waiting for a solution though.

**Comment by malles** [comment] 2015-06-30 11:30
Please try upgrading UIkit. http://codepen.io/malles/pen/jEvooV
It works fine in current version.

**Closed by malles** 2015-06-30 11:30 UTC
