### ISSUE TITLE
ScrolSpy not working anymore

### ISSUE THREAD

**Issue by kraymitchell** [uikit/uikit#1219] opened 2015-04-30 22:06 UTC
I have a couple of these in my site:
`<h1><i class="uk-icon-plug uk-icon-large uk-scrollspy-init-inview" data-uk-scrollspy="{cls:'uk-animation-scale-up', delay:200}"></h1>`

and they were working fine. I updated the JS and CSS files with the latest (2.20.2) from the site and now they no longer work at all. Nothing appears just blank space. Double checked that nothing for ScrollSpy changed on the website with the update and I'm not seeing anything.

Went back to old CSS and JS and no issues. Not sure which version they were from exactly.

**Comment by malles** [comment] 2015-04-30 22:38
You don't need the `uk-scrollspy-init-inview` class on your element, that is added by the javascript.
Does the effect work with another animation, eg `fade`? The `scale-up` animation is broken in the docs at the moment, but I don't think the releases are or have been.

**Comment by malles** [comment] 2015-04-30 22:47
Oh, and the closing `i`-tag is missing :)

**Comment by kraymitchell** [comment] 2015-04-30 23:03
Thanks Malles
OK, the missing i was bad copy and paste. Missed it in the copy and when I manually wrote the closing H2 LOL.

Fade is working when the init-inview is removed, but the scale-up does not work still.

**Comment by malles** [comment] 2015-05-01 06:49
Hmm. That may mean it has broken.. I can't recreate it in a codepen though. http://codepen.io/malles/pen/waBgEK It works fine (Icons don't work in Codepen.) Can you check in the debugger if it's the same problem as #1207 ?

**Comment by kraymitchell** [comment] 2015-05-01 13:00
I can check this tonight. However, I don't have any docs css files, is that going to matter at all?
I don't even see docs css files in the UIkit package...

**Comment by malles** [comment] 2015-05-01 13:11
That is correct, you shouldn't have the docs css. The bug in the UIkit site is in that file and I presumed (hoped) it is not in the regular css. If you find `uk-fade-scale02` instead of `uk-fade-scale-02` as animation name in the css, the problem is bigger.

**Comment by aheinze** [comment] 2015-05-04 10:18
the ```uk-fade-scale02``` issue will be fixed with the upcoming release. the was a bug in the build tools.

**Closed by aheinze** 2015-05-04 10:18 UTC
