### ISSUE TITLE
Tooltip title Reset to blank : title=""

### ISSUE THREAD

**Issue by JoeMac90** [uikit/uikit#3146] opened 2018-01-17 00:52 UTC
### UIkit version 
3.0.0-beta.37

### Browser
Firefox Nightly 59.0a1 (2018-01-16) (64-bit)
Firefox Nightly  58.0b16 (64-bit)

### Reproduction Link

I have only experienced problems with this version of 3.0.0-beta.37.
In a web page is using tooltips on a uk-scrollspy-nav, the title text is reset.

i.e. title=""

The problem is exhibited in my web (not attached) and is also not working in the uikit tooltip test page:
https://getuikit.com/assets/uikit/tests/tooltip.html

The small codepen example works correctly:
https://codepen.io/anon/pen/MrPKQO

### Steps to reproduce

https://getuikit.com/assets/uikit/tests/tooltip.html

### What is Expected?
Tool tip : title="text"
### What is actually happening?
Tool tip : title=""

**Comment by TomS-** [comment] 2018-01-17 09:30
I can't seem to reproduce this.
I've tried your codepen on Chrome and Firefox (non-nightly) - I was experiencing something like this recently and a fix was pushed.

It's possible that this is only happening in the Firefox nightly.

**Comment by jsieler** [comment] 2018-01-17 11:09
I'm using firefox stable, latest version, having same issue. Title value is being reset to empty.

**Comment by jsieler** [comment] 2018-01-17 11:15
Found where the issue is: https://github.com/uikit/uikit/blob/f59f78f74711a26a8f3bfad47fbab6044556153d/src/js/components/tooltip.js#L35
Switching `title: ''` to `title: null` makes it work.

Strange, but in v36 it was null by default. Wonder why it was changed.

**Comment by JoeMac90** [comment] 2018-01-17 11:27
Nightly 58.0b16 & Stable 57.0.4 with two different PC's
It works with:
https://getuikit.com/docs/tooltip
https://codepen.io/anon/pen/wpYmjO
but not:
https://getuikit.com/assets/uikit/tests/tooltip.html

Although on a colleges PC it works with Nightly 58.0b16. and Chrome

**Comment by TomS-** [comment] 2018-01-17 11:32
@jsieler I don't know why it was changed, it was changed to apparently fix this bug. However, I like @JoeMac90 am not getting this bug? 

Strange it has different results computer to computer. Maybe it's cached?

**Comment by jsieler** [comment] 2018-01-17 11:38
Found out. Minified version is working well, while not minified no. Probably, thru the minification some values are changed, which makes it work.

**Comment by TomS-** [comment] 2018-01-17 11:51
@jsieler it might change :'' to :false or :0

**Comment by janschoenherr** [comment] 2018-01-17 12:49
This is fixed with f59f78f74711a26a8f3bfad47fbab6044556153d. Thanks.

**Comment by janschoenherr** [comment] 2018-01-18 10:20
Resolved with beta 38

**Closed by janschoenherr** 2018-01-18 10:20 UTC
