### ISSUE TITLE
uk-tab non responsive

### ISSUE THREAD

**Issue by tawandabrandon** [uikit/uikit#2964] opened 2017-10-27 05:47 UTC
I've been trying yp implement a tab on my v3 Beta 31 project and it hasn't been working, even the test snippets from here:

https://getuikit.com/assets/uikit/tests/tab.html

**Comment by robertboloc** [comment] 2017-11-02 12:09
I can confirm we are experiencing the same issue. Tabs are not working at all. Rolling back to beta 30 works fine and beta 32 is still broken so it has to be something in beta 31 that broke it.

Thanks,
Rob

**Comment by janschoenherr** [comment] 2017-11-03 14:12
Could you be more specific, on what is not working?

The Tab tests are without any content. Were you looking for the Tab section in the Switcher tests?
https://getuikit.com/assets/uikit/tests/switcher.html

**Comment by robertboloc** [comment] 2017-11-04 10:38
When using the beta 30 the clicked item gets set the `uk-active` class on click like here: https://codepen.io/anon/pen/MOyEGo but since beta 31 that does not happen anymore https://codepen.io/anon/pen/qVZPYM

I hope this helps. Thanks

Thanks,
Rob

**Comment by janschoenherr** [comment] 2017-11-07 08:29
Thanks, fixed with 9bce9d3bb33cc5fa600dfec482e754c24316b746

**Closed by janschoenherr** 2017-11-07 08:29 UTC
