### ISSUE TITLE
Double uk-icon when inside vue.js instance element

### ISSUE THREAD

**Issue by Tasssadar** [uikit/uikit#2519] opened 2017-03-13 13:34 UTC
### UIkit version

3.0.0-beta.18

### Reproduction Link
https://jsfiddle.net/egw6ha1g/6/ (every time in chrome & firefox, 2s timer)
https://jsfiddle.net/egw6ha1g/4/ (every time in chrome, sometimes in firefox)
(search for uk-icon in the HTML)
(this is race condition, if vue.js loads first then the problem doesn't manifest itself)

http://i.imgur.com/4kIJslD.png

### Steps to reproduce
Put an element with `uk-icon` tag inside of vue.js instance element.

### What is Expected?
One icon appears.

### What is actually happening?
Two icons appear.

I'm assuming this is because vue.js re-adds the elements after it parses them, causing uikit notice another uk-icon tag and it just adds the icon. Not sure if this is uikit or vue.js bug.

**Comment by janschoenherr** [comment] 2017-03-13 16:17
> (this is race condition, if vue.js loads first then the problem doesn't manifest itself)

Yes, UIkit needs to run after Vue. Otherwise, UIkit will already have altered the markup, that is used by Vue as template. We currently don't know how to handle this well.

**Comment by Tasssadar** [comment] 2017-03-14 15:32
So, the solution seems to be to load uikit.js last, with `defer` specified, and initialize Vue.js instances immediately instead of in onload event handler. This means there is gonna be a frame or more of broken page visible before the uikit js loads, and seems prone to breaking. UIkit documentation website uses this method, but since all content is added by js, the broken page is not visible.

**Comment by yiyunzhi** [comment] 2017-04-06 20:52
I have same issue

**Comment by bryaneburr** [comment] 2017-04-12 08:18
+1

This happened to me as well - ironically the page loads correctly now due to the presence of a navbar with `uk-sticky` - uikit found the additional sticky placeholder but couldn't properly access the element:
```
uikit.js:4839 Uncaught TypeError: Cannot read property 'css' of null
    at Sticky.write (uikit.js:4839)
    at uikit.js:1536
    at runTasks (uikit.js:610)
    at flush (uikit.js:597)
```

I suppose if you want a horribly kludgey way of dealing with this problem, add a `uk-sticky` element near the top of your page and then letting it error out. Not the kind of behavior I would ever want to endorse, but you might find it works until a fix comes out.

**Comment by rossity** [comment] 2017-04-29 11:31
@bryaneburr THANK YOU

**Comment by rossity** [comment] 2017-04-29 13:38
@bryaneburr Thank you. This works well! Unfortunately it doesn't work with "uk-close" (the close icon doubles) inside of modals. Any idea of a fix?

**Comment by bryaneburr** [comment] 2017-04-29 19:20
This is what I did (an off-canvas element, for example):
```
<button class="uk-offcanvas-close" type="button">
   <span uk-icon="icon: close"></span>
</button>
```
Pretty easy 😄, although I can't guarantee it will be this simple for *all* components. But the gist is to not use `uk-close`, and instead just use the icon directly (since we now know this works 😉).

**Comment by rossity** [comment] 2017-04-29 23:02
@bryaneburr Thank you for the suggestion!! I think it will have to do for now. Doesn't look as clean as `uk-close` but it works in the short term!

**Comment by Nayar** [comment] 2017-05-13 16:09
Tried the defer method, less duplicates but they still occur

**Comment by ruchern** [comment] 2017-05-13 18:45
I have this issue when I fire the back button. Also using Vue just like others ITT.

**Comment by tshafer** [comment] 2017-07-01 17:10
The above method works for me.

**Comment by staticwave** [comment] 2017-07-10 02:28
For what it's worth, I prefer assigning the icons to the vue instance data
```
data: {
        icons: {
            contact: 'user',
            address: 'location',
            phone: 'phone',
            email: 'mail',
            fax: 'copy',
            url: 'laptop',
            open: 'chevron-up',
            close: 'chevron-down'
        }
}
```

And then using it like this

`<span :uk-icon="'icon: ' + icons.contact"></span>`

I no longer have the double icon issue inside vue instances. Hope that helps!

**Comment by Imperyall** [comment] 2017-07-12 13:48
I found a simpler solution
`<span :uk-icon="'icon: contact'"></span>`

**Comment by da-z** [comment] 2017-10-13 11:53
With 3.0.0-beta.30, I had the same issue and used the tip @Imperyall proposed. Strange, because this should have been fixed in beta.27.

Anyway, I noticed that tooltips don't work as well, and, using the same convention I found :uk-tooltip="''" to be working. However, I have no idea why I have to do this.

**Comment by DenisAlliswell** [comment] 2017-10-21 18:39
@rossity method works.

**Comment by tanoabeleyra** [comment] 2017-12-21 22:01
> @janschoenherr: Yes, UIkit needs to run after Vue. Otherwise, UIkit will already have altered the markup, that is used by Vue as template. We currently don't know how to handle this well.

There's still a problem if UIkit runs after Vue.

UIkit 3 applies CSS classes automatically using JavaScript. For example, when using the `uk-icon` attribute there's no need to apply the `.uk-icon` class. The problem is that, if I run UIkit after Vue, then Vue won't realize that a class was applied by UIkit. Later, when adding a class with Vue, the `.uk-icon` class will be gone.

What's the right way to deal with this?

**Comment by jsmsalt** [comment] 2018-01-07 20:03
This is not a solution, but a temporary workaround until this issue is fixed.

**sass**:
```
.uk-icon {
	>svg {
		&:nth-child(2) {
			display: none;
		}
	}
}
```
**css**:
`.uk-icon>svg:nth-child(2) {display: none;}`

**Comment by SaphiLC** [comment] 2018-11-29 00:50
still happens, RC24... i dont want to use the icons but some components have some icons that are duplicated, like modal close... can you PLEEEEEEASE, remove the icons so instead of adding a uk-close we are free to add whatever icon we want inside the element?

**Comment by zzseba78** [comment] 2018-12-11 15:00
To me seems like it´s fixed in RC 25

**Closed** 2019-07-11 14:03 UTC
