### ISSUE TITLE
UIKit render icon in VueJs app scope

### ISSUE THREAD

**Issue by blackcatpolice** [uikit/uikit#2357] opened 2017-02-07 07:09 UTC
There is a issue when uikit render icon, it will append everytime dom element change, but when I use vuejs, the dom elements always change if I "new Vue()", so will it judgment an icon element chilren have a svg element, if true return, don't need append again. 

And this my code:

#line4236 
` if (this$1.$el.children('svg').length >= 1) {
                                return;
                            }`

**Comment by Nayar** [comment] 2017-02-24 05:26
Having it too in beta 12

![screen shot 2017-02-24 at 9 25 28 am](https://cloud.githubusercontent.com/assets/454815/23291653/54d1a786-fa73-11e6-90ad-14282039ff83.png)

**Comment by janschoenherr** [comment] 2017-03-01 17:29
Fixed in Beta 13. 

https://getuikit.com/docs/icons

**Comment by Nayar** [comment] 2017-03-08 19:04
seems to have come back in beta 16 :(

**Comment by janschoenherr** [comment] 2017-03-09 10:18
Please provide a reproduction link. You could start with this template: http://codepen.io/anon/pen/XMpryM

**Comment by Nayar** [comment] 2017-03-09 18:00
You can see on my still in dev website here: https://logs.nayarweb.com/shop

**Comment by yiyunzhi** [comment] 2017-04-06 21:14
come back in beta 20 again :(, unless uikit-icons.min.js defer loaded

**Comment by gtapps** [comment] 2017-05-23 02:14
+1

**Comment by giordanovi** [comment] 2017-12-10 19:47
+1

**Comment by illjah42** [comment] 2018-08-11 07:42
+1
https://codepen.io/illjah42/pen/RQyLob

**Comment by janschoenherr** [comment] 2019-07-11 13:40
I believe this has since been resolved.

**Closed by janschoenherr** 2019-07-11 13:40 UTC
