### ISSUE TITLE
Upload component with "multiple: false" fails

### ISSUE THREAD

**Issue by salsaandi** [uikit/uikit#4587] opened 2022-03-16 16:55 UTC
### UIkit Version

3.12.2
It works well in previous versions.

### Browser

All browsers

### Actual Behavior

Error in Upload component with "multiple: false" initialisation.

The script fails at beginning of uploading a file, because it tries to slice the list of uploaded files but it is not slicable. 

It gives:
 **Uncaught (in promise) TypeError: t.slice is not a function**

### Workaround

It works with a single file input 
```
<input type="file">
```
and a multi file initialization
```
multiple: true
```
but should be fixed or the parameter removed.

**Comment by janschoenherr** [comment] 2022-03-18 12:16
Should be fixed with v3.13.0

**Closed by janschoenherr** 2022-03-18 12:16 UTC
Labels: ! Bug

**Comment by timrasche** [comment] 2022-03-28 14:16
Sorry its not fixed... Whole component broken

**Comment by janschoenherr** [comment] 2022-03-29 07:32
Please be a bit more specific, is it the same error as above?

`Uncaught (in promise) TypeError: t.slice is not a function`

**Comment by timrasche** [comment] 2022-03-29 07:33
> Please be a bit more specific, is it the same error as above?
> 
> `Uncaught (in promise) TypeError: t.slice is not a function`

Yes it is

**Comment by janschoenherr** [comment] 2022-03-29 08:01
I can't reproduce the error. It seems to be working here: https://getuikit.com/assets/uikit/tests/upload.html

**Comment by timrasche** [comment] 2022-03-29 08:03
Remove the "multiple" attribute, that produces the error.
