### ISSUE TITLE
Drop down opens up initially when page loads

### ISSUE THREAD

**Issue by theromie** [uikit/uikit#2847] opened 2017-08-16 11:08 UTC
### UIkit version

3.0.0-beta.28

### What is Expected?
should not display dropdown

### What is actually happening?
Drop down opens up initially when page loads
![dropdown](https://user-images.githubusercontent.com/11131555/29360621-64453492-82a1-11e7-8496-dc3ecb22a96f.png)

**Comment by theromie** [comment] 2017-08-16 11:49
even i did network recording in dev tools.
![dropdown](https://user-images.githubusercontent.com/11131555/29361845-fefa7448-82a6-11e7-8f0b-f3a381cc8995.png)

**Comment by janschoenherr** [comment] 2017-08-18 12:46
Duplicate of #2851?

**Closed by janschoenherr** 2017-08-18 12:46 UTC
