### ISSUE TITLE
[Feature Request] Add datepicker

### ISSUE THREAD

**Issue by keeferrourke** [uikit/uikit#2870] opened 2017-09-02 17:56 UTC
It would be really nice if UIKit could add a simple date/time picker to its form collection.

This could be something as simple a having some element:
```
<input type="text" class="uk-datepicker">
```
Where, clicking on the input element would display a pop-up calendar; selecting a date on the calendar would populate the text-field with a date-string properly formatted for the selected locale.

Any chance this could be implemented?

**Comment by nixgadget** [comment] 2017-09-03 09:23
There is an existing request for this feature already.

**Comment by keeferrourke** [comment] 2017-09-03 18:27
@nixgadget the open issues regarding date/time pickers (https://github.com/uikit/uikit/issues/2789, https://github.com/uikit/uikit/issues/2781, https://github.com/uikit/uikit/issues/2723) are not clearly written, and the conversations on them appear to be dead. Hence, this issue.

Please mark this as a duplicate issue if necessary, but I think it should be more clear if this is being worked on.

**Comment by aarongerig** [comment] 2017-09-03 18:31
As far as I know, it's not being worked on. At least not for now... I'd recommend you using a 3rd party lib to accomplish that.

**Comment by keeferrourke** [comment] 2017-09-03 18:43
I'm probably going to end up skipping the date-picker for the project I'm working on at the moment (simply due to time-constraints), but thanks for letting me know. Anyway, it would definitely be a welcome addition to the library for many front-end devs. Cheers.

**Comment by marcorensch** [comment] 2017-09-12 12:55
+1

**Comment by janschoenherr** [comment] 2017-11-07 14:49
Will close this for now, as you've already mentioned, its a duplicate of #2781

**Closed by janschoenherr** 2017-11-07 14:49 UTC
