### ISSUE TITLE
Scrollbar is missing when closing modal using `uk-modal-close`

### ISSUE THREAD

**Issue by lesaff** [uikit/uikit#1355] opened 2015-06-22 12:55 UTC
My scrollbar disappeared when I closed my modal window using `uk-modal-close` trigger. Closing the modal by clicking on modal overlay works fine.

Tested using `v 2.21.0` on OSX Yosemite with Chrome 43.0.2357.124 (64-bit)

Update:
Also seeing the issue with Safari 8.0.6
Firefox 38.0.5 works fine

**Comment by malles** [comment] 2015-11-23 14:09
Do you still have this issue?

**Comment by prtome** [comment] 2016-01-09 17:46
Hello
I have the same issue. I fire a modal that has a form in it, close it (submit or cancel) and my underlying window does not scroll anymore.
I am currently using 2.23.0 on OS X El Capitan, Safari 9.02 and Chrome  47.0.2526.106 (64-bit)

**Comment by malles** [comment] 2016-04-10 22:49
It is mostly caused by a lost reference to the modal. Can you show an example?

**Comment by philoest** [comment] 2017-01-12 13:24
We have released the next major version, UIkit3. To start focusing our work on the most recent release, we decided to close all the issues related to UIkit2. Please check, if these issues still persist in version 3 and if so, please open a new issue.

Thanks for your understanding,
Your UIkit Team

**Closed by philoest** 2017-01-12 13:24 UTC
