### ISSUE TITLE
Please add Out animations to Dropdown and Drop component ( or remove it from the docs )

### ISSUE THREAD

**Issue by zzseba78** [uikit/uikit#2976] opened 2017-10-30 14:33 UTC
### UIkit version

3.0.0-beta.32

### Browser
Chrome, Safari, FF
### Reproduction Link

The docs.

#### According to the docs:
>**animation**: Space separated names of animations to apply. Comma separate for out animations.

#### And in component events documentation.

> **hide** | Fires after an item's hide animation has started.

>**hidden** | Fires after an item is hidden.

### What is actually happening?
Dropdown and Drop component doesn´t have a OUT animation, it would be great to have it,  implemented correctly it can enhance a UI. And if you don´t want an out animation...simple, don´t put a second animation ( it´s the default ).

**It´is very confusing that this are mentioned in the docs but aren't functional.**

**Comment by janschoenherr** [comment] 2017-11-03 13:27
Duplicate of #2809. 

Docs are fixed: uikit/uikit-site@adc6572b4492638dcae18340f77f8e1ad4414f32 and 7e95507eb6a2dfcdd13c1253920c91d9ef48239a

**Closed by janschoenherr** 2017-11-03 13:27 UTC
