### ISSUE TITLE
Reggression: Navbar - no left and right margin applied

### ISSUE THREAD

**Issue by buca92** [uikit/uikit#4648] opened 2022-07-25 04:57 UTC
Hello UIKit team,

it seems there, in Navbar, is regression in your last version 3.15.1. There is no neither left nor right margin applied in case of Navbar items. It is even obvious in you docs: https://getuikit.com/docs/navbar 

### UIkit Version

3.15.1

### Actual Behavior

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5333489/180701021-4dd8570a-6385-4d8d-b612-fac647bf54ec.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5333489/180701062-9e3a6208-d291-47ef-b235-b404bf75b41e.png">

It is really ugly and ruins existing apps.

### Expected Behavior

Left and right margin should be provided again to get it consistent with previous behaviour.

**Comment by buca92** [comment] 2022-08-01 06:02
Any update here?

**Comment by kingroho** [comment] 2022-08-06 23:49
still having the bug..

**Comment by buca92** [comment] 2022-08-07 04:19
Well, if you put ^3.12.0 into package.json then you still get the latest version 3.15.x after installing it. You probably do not know what the ^ does: https://michaelsoolee.com/npm-package-tilde-caret/ .

 At the time I installed the uikit (a few weeks ago) the version 3.14.0 was used. And margin was applied there, I am sure. But, after `npm update` the version 3.15.1 was installed and martin is gone since the time.

It is also obvious in official documentation that the margin is gone.

I am sure it is regression in UIKit.

**Comment by kingroho** [comment] 2022-08-07 08:50
oh! Thank you for clarifying that. Indeed, I did not know what does a tilde and a caret means. So it's still using the 3.15.1 :)

**Comment by thathoff** [comment] 2022-08-16 11:52
I can confirm this issue.

**Comment by janschoenherr** [comment] 2023-09-15 13:56
Duplicate of #4638

**Closed by janschoenherr** 2023-09-15 13:56 UTC
Labels: ! Bug
