### ISSUE TITLE
Off-Canvas Container moved outside of form element

### ISSUE THREAD

**Issue by viewpoint** [uikit/uikit#2966] opened 2017-10-27 16:05 UTC
### UIkit version

3.0.0-beta.31

### Browser
Chrome

### Steps to reproduce
BEFORE SHOW OFF CANVAS EVENT
`<body>`
`    <form>`
`        <div class="uk-offcanvas-content">`
`            <!-- page content here-->`
`        </div>`
`        <div id="offcanvas1" uk-offcanvas>`
`            <!-- off-canvas form elements here-->`
`        </div>`
`    </form>`
`</body>`

AFTER SHOW OFF CANVAS EVENT
`<body>`
`    <form>`
`        <div class="uk-offcanvas-content">`
`            <!-- page content here-->`
`        </div>`
`    </form>`
`    <div id="offcanvas1" uk-offcanvas>`
`        <!-- off-canvas form elements here-->`
`    </div>`
`</body>`

### What is Expected?
I would NOT expect the off-canvas to be moved at all, however, at the very least I would expect it to be moved to 'just before the closing `</form>` tag, rather than the closing `</body>` tag.

### What is actually happening?
You will notice the off-canvas container is moved to just before the closing `</body>` tag.
This moves the off-canvas container to the OUTSIDE of the `</form>` tag. As such, forms inside off-canvas divs DO NOT work.

### WORKAROUND
Include your entire `<form></form>` tags INSIDE the off-canvas `<div>` container.

### PROBLEM
The suggested WORKAROUND is not possible for Microsoft asp.net pages. The `<form>` element is typically the first and last tag on the page, and cannot easily be moved to inside an off-canvas `<div>` container. Therefore, the solution would be be move the off-canvas container div to just before the closing `</form>` tag.

**Comment by MrFragIT** [comment] 2017-10-30 16:47
I had a similar problem, fixed by setting a container id for the offcanvas.

Take a look at this: #2649

**Comment by janschoenherr** [comment] 2017-12-13 11:02
That is currently intended behavior. Setting the `container`option to `false` will prevent this behavior in the next version.

**Closed by janschoenherr** 2017-12-13 11:02 UTC
