### ISSUE TITLE
plugin.call() is not a function

### ISSUE THREAD

**Issue by Zedonboy** [uikit/uikit#3914] opened 2019-07-11 23:03 UTC
### UIkit version

3.1.6

### Steps to reproduce
create a js file
```
import UIkit from "uikit/dist/js/uikit-core"
import notification from "uikit/src/js/components/notification"

UIkit.use(notification);

export default UIkit;
```
add this file in your entry file in webpack 4,

### What is Expected?
Expect my app to run
### What is actually happening?
but crashes with runtime error
Am seeing error plugin.call() is not a function @Uikit.use

**Comment by aarongerig** [comment] 2019-07-12 08:48
Duplicate of https://github.com/uikit/uikit/issues/3913

**Closed by aarongerig** 2019-07-12 08:48 UTC
