### ISSUE TITLE
Allow searching in the docs

### ISSUE THREAD

**Issue by isometriq** [uikit/uikit#3343] opened 2018-04-20 06:25 UTC
In the docs here:
https://getuikit.com/docs/

Search functionality in the docs would be very useful. I find it difficult to know the exact component to use when something needs to be done, especially when using uikit sparsely. It is confusing having to browse many component doc pages for a simple usage.

**Comment by peterbrinck** [comment] 2018-04-20 09:25
I definitely agree with this one.

Even as an avid user of UIkit, I sometimes have trouble finding the right thing.
I think it could be done the same Laravel has done their search, https://laravel.com/docs/5.6, as it works really great for documentations

**Comment by zzseba78** [comment] 2018-04-20 14:15
Duplicate of https://github.com/uikit/uikit/issues/3277

**Comment by janschoenherr** [comment] 2019-10-02 08:27
https://github.com/uikit/uikit-site/issues/93

**Closed by janschoenherr** 2019-10-02 08:27 UTC
