### ISSUE TITLE
Offcanvas bug Progress style when opening on iOs

### ISSUE THREAD

**Issue by jonasmarco** [uikit/uikit#4790] opened 2023-05-29 14:37 UTC
### UIkit Version

_Check if the issue is reproducible with the latest stable version._
^3.5.13

### Actual Behavior

When a canvas is opened, the Progress style is changed, iOS only

Before opening the off canvas:
![WhatsApp Image 2023-05-29 at 11 26 13](https://github.com/uikit/uikit/assets/19959770/b9c24719-409c-499c-95d2-688d9e9f9952)

After opening the off canvas:
![WhatsApp Image 2023-05-29 at 11 24 46](https://github.com/uikit/uikit/assets/19959770/6f2e7842-0d90-4e4e-8706-15e5835e931a)

### Expected Behavior

Keep Progress css style

https://codepen.io/jonasmarco/pen/WNaBxBx

I couldn't simulate the same error that happens on my site in codepen, on my site after scrolling the style remains blue (like on the print), in codepen we can see that when the offcanvas is opened the progress style changes

**Comment by janschoenherr** [comment] 2023-06-12 08:28
Duplicate of https://github.com/uikit/uikit/issues/4636

**Closed by janschoenherr** 2023-06-12 08:28 UTC
Labels: ! Bug

**Comment by janschoenherr** [comment] 2023-06-12 09:17
I can no longer reproduce the issue with that commit. Did you recompile the JavaScript?
